### PR TITLE
Fixed Grafana detector

### LINKED ISSUE #4157: Grafana detector does not differentiate between `InvalidCredentials` and `Unauthorized`
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
Latest

### Trace Output

N/A

### Expected Behavior

The Grafana detector handles different error responses.

**Token is not valid**
```
Response: status=401, body={
  "code": "InvalidCredentials",
  "message": "Token invalid",
  "requestId": "6acbfb1f-a551-48f3-9935-8b2f092edbc9"
}
```

**Token is valid but has restricted permissions**
```
Response: status=401, body={
  "code": "Unauthorized",
  "message": "invalid permission: access policy missing required scope [accesspolicies:read], received [metrics:write, metrics:import, logs:write, traces:write, alerts:write, rules:write, profiles:write, datadog:validate]",
  "requestId": "7d4df303-9e48-41ad-8e20-d496dee86052"
}
```

### Actual Behavior

Both `InvalidCredentials` and `Unauthorized` (valid but insufficient permissions) are treated as unverified.

### Steps to Reproduce

1. Scan a Grafana token with limited permissions

## Environment
N/A

## Additional Context
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by kashifkhan0771**
### Description:
Related to #4157 

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/detectors/grafana/grafana.go [hunk 1]
```diff
@@ -85,3 +75,41 @@ func (s Scanner) Type() detectorspb.DetectorType {
 func (s Scanner) Description() string {
 	return "Grafana is an open-source platform for monitoring and observability. Grafana API keys can be used to access and manage Grafana resources."
 }
+
+func verifyGrafanaKey(ctx context.Context, client *http.Client, token string) (bool, error) {
+	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://grafana.com/api/v1/tokens?region=us", http.NoBody)
```
Comment (shahzadhaider1) [inline pkg/detectors/grafana/grafana.go:80]: Could there be any other regions? More specifically, can there be scenarios where one token might be for some region other than us?

**Review by amanfcp — APPROVED** [review]
LGTM.

File: pkg/detectors/grafana/grafana.go (hunk 1 above)
Comment (kashifkhan0771) [reply pkg/detectors/grafana/grafana.go:80]: Grafana Tokens are not tied to any specific region.

**Review by shahzadhaider1 — APPROVED** [review]

File: pkg/detectors/grafana/grafana.go [hunk 2]
```diff
@@ -23,13 +24,22 @@ var _ detectors.Detector = (*Scanner)(nil)
 var (
 	defaultClient = common.SaneHttpClient()
 	// Make sure that your group is surrounded in boundary characters such as below to reduce false positives.
-	keyPat = regexp.MustCompile(`\b(glc_[A-Za-z0-9+\/]{50,150}\={0,2})`)
+	keyPat = regexp.MustCompile(`\b(glc_eyJ[A-Za-z0-9+\/=]{60,160})`)
```
Comment (kashifkhan0771) [inline pkg/detectors/grafana/grafana.go:27]: I generate around 10 tokens and each one of them was detected by this regex. Earlier few tokens suffix was being trim due to 150 character limit.

Comment (kashifkhan0771) [inline pkg/detectors/grafana/grafana.go:27]: I generated around 10 tokens, and each one was successfully detected by this regex. Previously, some token suffixes were getting trimmed due to the 150-character limit.

File: pkg/detectors/grafana/grafana.go [hunk 3]
```diff
@@ -85,3 +75,41 @@ func (s Scanner) Type() detectorspb.DetectorType {
...
+		if err != nil {
+			return false, err
+		}
+
+		// token is valid but has restricted permissions
+		if strings.Contains(string(bodyBytes), "Unauthorized") {
+			return true, nil
+		}
+
+		return false, nil
```
Comment (nabeelalam) [inline pkg/detectors/grafana/grafana.go:111]: Nit: These lines could be simplified to:
```
	case http.StatusUnauthorized:
		bodyBytes, err := io.ReadAll(resp.Body)
		if err != nil {
			return false, err
		}

		// token is valid but has restricted permissions
		return strings.Contains(string(bodyBytes), "Unauthorized"), nil
```
Just more concise and feels a bit more idiomatic.

**Review by nabeelalam — APPROVED** [review]
Looks great! Thanks @kashifkhan0771
