### PR TITLE
Fixed Kontent Detector

### LINKED ISSUE #1650: Kontent Detector Producing False Positives
### TruffleHog Version
`trufflehog 3.52.1`

### Expected Behavior
TH should detect valid Kontent Delivery API Keys and Management API Keys. See detailed documentation here: https://kontent.ai/learn/docs/apis/api-keys

### Actual Behavior
TH currently detects Kontent Environment ID values, which are PUBLIC. It does not detect API Keys. The [URI used for verification](https://github.com/trufflesecurity/trufflehog/blob/5cfbde783f23cce4c51a92ea0915846b9c532ecc/pkg/detectors/kontent/kontent.go#L51) in the detector is supposed to be public (this is how their Headless CMS product delivers content).

### PR DESCRIPTION
**Pull request by kashifkhan0771**
### Description:
This PR fixes Kontent Detector. More details can be found in #1650 

### Tests:
Screenshot from 2025-05-06 16-52-06

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/detectors/kontent/kontent.go [hunk 1]
```diff
@@ -34,31 +39,32 @@ func (s Scanner) Keywords() []string {
...
+	for _, apiKey := range apiKeyPat.FindAllStringSubmatch(dataStr, -1) {
+		uniqueAPIKeys[apiKey[1]] = struct{}{}
+	}
 
-		s1 := detectors.Result{
-			DetectorType: detectorspb.DetectorType_Kontent,
-			Raw:          []byte(resMatch),
-		}
+	for _, envID := range envIDPat.FindAllStringSubmatch(dataStr, -1) {
+		uniqueEnvIDs[envID[1]] = struct{}{}
```
Comment (abmussani) [inline pkg/detectors/kontent/kontent.go:49]: False positive UUIDs can be excluded by lower entropy condition and checking in [Known FP UUIDs](https://github.com/trufflesecurity/trufflehog/blob/426d08b31602ef67c7cf99128302b5992a7c0d33/pkg/detectors/azure_entra/common.go#L54).

File: pkg/detectors/kontent/kontent.go [hunk 2]
```diff
@@ -34,31 +39,32 @@ func (s Scanner) Keywords() []string {
...
-		if verify {
-			req, err := http.NewRequestWithContext(ctx, "GET", fmt.Sprintf("https://deliver.kontent.ai/%s/items", resMatch), nil)
-			if err != nil {
-				continue
+	for envID := range uniqueEnvIDs {
+		for apiKey := range uniqueAPIKeys {
+			s1 := detectors.Result{
+				DetectorType: detectorspb.DetectorType_Kontent,
+				Raw:          []byte(envID),
+				RawV2:        []byte(envID + apiKey),
```
Comment (abmussani) [inline pkg/detectors/kontent/kontent.go:57]: @rosecodym do we have any implication on enterprise if results started to include `RawV2` ?

Comment (kashifkhan0771) [reply pkg/detectors/kontent/kontent.go:57]: I believe that if any secrets related to this detector exist in the enterprise, they are likely to be false positives or not useful. Previously, the detector was only detecting the environment ID, not the actual API key. While the environment ID is required for an API call, the truly sensitive information is the API key itself.

File: pkg/detectors/kontent/kontent.go (hunk 1 above)
Comment (kashifkhan0771) [reply pkg/detectors/kontent/kontent.go:49]: Thank you for the suggestion ❤️ I added it

**Review by ahrav — APPROVED** [review]

File: pkg/detectors/kontent/kontent.go (hunk 2 above)
Comment (ahrav) [reply pkg/detectors/kontent/kontent.go:65]: Including `RawV2` to a previously detected secret that only had `Raw` is completely fine. 👍
