### PR TITLE
Fix GitParse trimming whitespace from filename

### LINKED ISSUE #2199: Git handle binary error: Not a valid object name
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

3.63.2

### Description

I received the following error from [`git.go:handleBinary`](https://github.com/trufflesecurity/trufflehog/blob/d1a2d9e83264da0a75410cd1736576c47a8f87a4/pkg/sources/git/git.go#L1006) while testing a change.
```sh
/usr/bin/git -C /tmp/trufflehog-4221-3083267655/.git cat-file blob 39e5a45bff3534db1d8a91169c0e12709537a3f6:Lunch and Learn - HCDiag.pdf
fatal: Not a valid object name 39e5a45bff3534db1d8a91169c0e12709537a3f6:Lunch and Learn - HCDiag.pdf
```

At first, I thought that the issue was a lack of proper quoting/sanitation of paths that use spaces. However, further investigation revealed that TruffleHog seems to be trimming the path [here](https://github.com/trufflesecurity/trufflehog/blob/d1a2d9e83264da0a75410cd1736576c47a8f87a4/pkg/gitparse/gitparse.go#L611) which results in an invalid path/filename.

```sh
$ git rev-list --objects --all | grep Lunch
86e93bc715599767614cbc7f6b1bdba67db38e46 Lunch and Learn - Dynamic Secrets.pdf
3e17a1ae24e4e131be448d16bd81e66e89ced496 Lunch and Learn - Kubernetes Integration.pdf
d7b0592cf053a85faeb56994fb6334a789433c60 Lunch and Learn - Migrate from Vault OSS to Vault Enterprise.pdf
682795407cf4ecc5fb47cc6598c5cd4594f8d315 Lunch and Learn - Kubernetes Integration.pdf
c3f6e1b34307e0c99d1d54f90634d0b84d46128f  Lunch and Learn - HCDiag.pdf <-- notice the extra space before "Lunch"

$ git log --full-history --all -p
...
commit 39e5a45bff3534db1d8a91169c0e12709537a3f6
Author: jherreman <60401056+jherreman@users.noreply.github.com>
Date:   Tue Jan 25 19:57:41 2022 -0700

    Add files via upload

diff --git a/ Lunch and Learn - HCDiag.pdf b/ Lunch and Learn - HCDiag.pdf
new file mode 100644
index 0000000..c3f6e1b
Binary files /dev/null and b/ Lunch and Learn - HCDiag.pdf differ
...
```

Why would someone create a file that starts with whitespace? I don't know, but this is technically a bug.

### Steps to Reproduce

Scan https://github.com/hashicorp-services/Vault-Onboarding/. The problematic file is specifically in https://github.com/hashicorp-services/Vault-Onboarding/commit/39e5a45bff3534db1d8a91169c0e12709537a3f6.

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This fixes #2199.

### Checklist:
* [x] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

File: pkg/gitparse/gitparse.go [hunk 1]
```diff
@@ -608,7 +608,7 @@ func pathFromBinaryLine(line []byte) string {
 		return ""
 	}
 	bRaw := sbytes[1]
-	return strings.TrimSpace(string(bRaw[:len(bRaw)-7])) // drop the "b/" and " differ"
+	return string(bRaw[:len(bRaw)-8]) // drop the "b/" and " differ\n"
```
Comment (ahrav) [inline pkg/gitparse/gitparse.go:611]: Nice find!

**Review by ahrav — APPROVED** [review]
