### PR TITLE
(fix) Leading = in gitlab v1 token 

### LINKED ISSUE #3671: GitLab v1 detector: incorrect pattern resulting in false positives, 429 rate limits
The pattern for GitLab v1 tokens is erroneous. `\b` can only be used next to `a-zA-Z0-9_`, for any other characters it will either not match or match incorrectly.
https://github.com/trufflesecurity/trufflehog/blob/1e5aac44955de69cdcfdf30eb8b279bc1d0a477f/pkg/detectors/gitlab/v1/gitlab.go#L36

**Examples**

Given the following pattern:
```regexp
gitlab.+=\b([a-zA-Z0-9\-=_]{20,22})\b
```

This will not match at all:
```
gitlab_token=-abcdefghijklmnopqrst
```

This will not match the `-` at the end:
```
gitlab_token=abcdefghijklmnopqrst-
```

**Real world example**
 Almost every GitLab URL will be falsely detected.
```
Found unverified result 🐷🔑❓
Verification issue: unexpected HTTP response status 429
Detector Type: Gitlab
Decoder Type: PLAIN
// Line: `// https://docs.gitlab.com/ce/api/services.html#get-drone-ci-service-settings`
Raw result: get-drone-ci-service-
Version: 1
Line: 169
Link: https://github.com/gocardless/atlantis/blob/fa43febf60e6585cf324164be9aa1391a09d7d6f/vendor/github.com/lkysow/go-gitlab/services.go#L169
```

### PR DESCRIPTION
**Pull request by abmussani**
### Description:
The `GitLab` v1 detector is matching on leading `=` character which results in verification misses for potentially LIVE secrets. For `GITLAB_TOKEN=ABc123456789dEFghIJK`,

the v1 detector will produce a raw match of `=ABc123456789dEFghIJK` since the regex pattern accepts = as a valid character. This Pr fixes this issue.

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/detectors/gitlab/v1/gitlab.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func (Scanner) CloudEndpoint() string { return "https://gitlab.com" }
 
 var (
 	defaultClient = common.SaneHttpClient()
-	keyPat        = regexp.MustCompile(detectors.PrefixRegex([]string{"gitlab"}) + `\b([a-zA-Z0-9\-=_]{20,22})\b`)
+	keyPat        = regexp.MustCompile(detectors.PrefixRegex([]string{"gitlab"}) + `\b([a-zA-Z0-9\-_][a-zA-Z0-9\-=_]{19,21})\b`)
```
Comment (kashifkhan0771) [inline pkg/detectors/gitlab/v1/gitlab.go:36]: Can we remove `-` and `_` as well for the first character?

**Review by kashifkhan0771 — APPROVED** [review]
Just one minor non-blocking comment. Rest LGTM!

**Review by nabeelalam — APPROVED** [review]
LGTM

**Review by ahrav — APPROVED** [review]

**Review by shahzadhaider1 — APPROVED** [review]
