### PR TITLE
fix: throws error if dir not found

### LINKED ISSUE #3005: Git source doesn't check if directory exists
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
HEAD

### Description

When using TruffleHog with a `file://` uri, the scan will complete with a 0 exit code even if the directory doesn't exist.

```sh
$ ls /tmp/fake-dir/
ls: cannot access '/tmp/fake-dir/': No such file or directory
$ ./trufflehog git file:///tmp/fake-dir/
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2024-06-23T18:12:55-04:00       info-0  trufflehog      running source  {"source_manager_worker_id": "XIh5z", "with_units": true}
2024-06-23T18:12:55-04:00       info-0  trufflehog      finished scanning       {"chunks": 0, "bytes": 0, "verified_secrets": 0, "unverified_secrets": 0, "scan_duration": "4.326315ms", "trufflehog_version": "dev"}
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:
This PR relates to #3005 . If the directory is not found, the process returns an error message and exits.

Screenshot 2024-10-16 at 1 42 58 AM

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/sources/git/git.go [hunk 1]
```diff
@@ -327,10 +327,16 @@ func (s *Source) scanDir(ctx context.Context, gitDir string, reporter sources.Ch
 		// TODO: Figure out why we skip directories ending in "git".
 		return nil
 	}
+
+	// Check if the directory exists
+	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
+		return fmt.Errorf("directory does not exist: %s", gitDir)
+	}
```
Comment (rosecodym) [inline pkg/sources/git/git.go:334]: I believe this change is the only one that's needed. With just it applied, this is the output I get:
```
trufflehog (remotes/origin/HEAD *) % ./trufflehog git file:///oops
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2024-10-16T16:14:08-04:00	info-0	trufflehog	running source	{"source_manager_worker_id": "hN9fy", "with_units": true}
2024-10-16T16:14:08-04:00	error	trufflehog	error running scan	{"error": "engine failed to finish execution: fatal: directory does not exist: /oops"}
trufflehog (remotes/origin/HEAD *) % echo $?
1
```
Are you seeing something different?

Comment (sahil9001) [reply pkg/sources/git/git.go:335]: @rosecodym Thanks for the review, I have removed the code. Can you please check again?

**Comment by sahil9001** [comment]
@kashifkhan0771 Can you please review this minor PR? Thanks!

**Review by kashifkhan0771 — APPROVED** [review]

**Review by rosecodym — APPROVED** [review]
