### PR TITLE
Fixed gitlab detector

### LINKED ISSUE #4370: Custom Verifier are not working in new version
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
trufflehog 3.90.3

### Trace Output

`trufflehog filesystem test.txt --no-update  --verifier gitlab=https://private gitlab domain/ --only-verified  --debug

2025/08/07 10:36:52 [updater parent] run
2025/08/07 10:36:53 [updater parent] starting trufflehog
2025/08/07 10:36:53 [updater child#1] run
2025/08/07 10:36:53 [updater child#1] start program
2025-08-07T10:36:53+07:00       info-2  trufflehog      trufflehog 3.90.3
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2025-08-07T10:36:53+07:00       info-2  trufflehog      starting scanner workers        {"count": 8}
2025-08-07T10:36:53+07:00       info-2  trufflehog      starting detector workers       {"count": 64}
2025-08-07T10:36:53+07:00       info-2  trufflehog      starting verificationOverlap workers    {"count": 8}
2025-08-07T10:36:53+07:00       info-2  trufflehog      starting notifier workers       {"count": 8}
2025-08-07T10:36:53+07:00       info-0  trufflehog      running source  {"source_manager_worker_id": "wP05O", "with_units": true}
2025-08-07T10:36:53+07:00       info-2  trufflehog      enumerating source      {"source_manager_worker_id": "wP05O"}
2025-08-07T10:36:54+07:00       info-0  trufflehog      finished scanning       {"chunks": 1, "bytes": 650, "verified_secrets": 0, "unverified_secrets": 0, "scan_duration": "1.290521292s", "trufflehog_version": "3.90.3", "verification_caching": {"Hits":0,"Misses":1,"HitsWasted":0,"AttemptsSaved":0,"VerificationTimeSpentMS":1287}}
2025/08/07 10:36:54 [updater parent] prog exited with 0
2025/08/07 10:36:54 [updater parent] signal (urgent I/O condition) failed (os: process already finished), assuming child process died unexpectedly`

### Expected Behavior

Able to scan and validate gitlab token with custom endpoint (private gitlab)

### Actual Behavior

Unable to scan gitlab token, and validate it. Few versions before are able to scan it. 
Needed flag "--custom-verifiers-only" to be added in command to be able to validate it.

### Steps to Reproduce

 1. Run trufflehog using command "trufflehog filesystem test.txt --no-update  --verifier gitlab=https://gitlab.domain/ --only-verified  --debug"
 2. and scan the file that contains gitlab token 

## Environment
 OS: MacOS Sonoma 14.1.1 (23B81)

### References

* #0000

### PR DESCRIPTION
**Pull request by kashifkhan0771**
### Description:
Fixes: #4370 

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/detectors/gitlab/v1/gitlab.go [hunk 1]
```diff
@@ -67,29 +67,30 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
...
-			for _, endpoint := range s.Endpoints() {
+			s1 := detectors.Result{
+				DetectorType: detectorspb.DetectorType_Gitlab,
+				Raw:          []byte(resMatch),
+				ExtraData:    map[string]string{},
+			}
+			s1.ExtraData = map[string]string{
+				"rotation_guide": "https://howtorotate.com/docs/tutorials/gitlab/",
+				"version":        fmt.Sprintf("%d", s.Version()),
+			}
```
Comment (shahzadhaider1) [inline pkg/detectors/gitlab/v1/gitlab.go]:
```suggestion
		s1 := detectors.Result{
			DetectorType: detectorspb.DetectorType_Gitlab,
			Raw:          []byte(resMatch),
			ExtraData: map[string]string{
				"rotation_guide": "https://howtorotate.com/docs/tutorials/gitlab/",
				"version":        fmt.Sprintf("%d", s.Version()),
			},
		}
```

File: pkg/detectors/gitlab/v2/gitlab_v2.go [hunk 2]
```diff
@@ -59,20 +59,21 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
...
+		for _, endpoint := range s.Endpoints() {
+			s1 := detectors.Result{
+				DetectorType: detectorspb.DetectorType_Gitlab,
+				Raw:          []byte(resMatch),
+				ExtraData:    map[string]string{},
+			}
+			s1.ExtraData = map[string]string{
+				"rotation_guide": "https://howtorotate.com/docs/tutorials/gitlab/",
+				"version":        fmt.Sprintf("%d", s.Version()),
+			}
```
Comment (shahzadhaider1) [inline pkg/detectors/gitlab/v2/gitlab_v2.go]:
```suggestion
s1 := detectors.Result{
			DetectorType: detectorspb.DetectorType_Gitlab,
			Raw:          []byte(resMatch),
			ExtraData: map[string]string{
				"rotation_guide": "https://howtorotate.com/docs/tutorials/gitlab/",
				"version":        fmt.Sprintf("%d", s.Version()),
			},
		}
```

**Review by shahzadhaider1 — APPROVED** [review]
Minor (non-blocking) suggestions.

File: pkg/detectors/gitlab/v1/gitlab.go [hunk 3]
```diff
@@ -67,29 +67,29 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
...
-			ExtraData:    map[string]string{},
-		}
-		s1.ExtraData = map[string]string{
-			"rotation_guide": "https://howtorotate.com/docs/tutorials/gitlab/",
-			"version":        fmt.Sprintf("%d", s.Version()),
-		}
+		for _, endpoint := range s.Endpoints() {
+			s1 := detectors.Result{
+				DetectorType: detectorspb.DetectorType_Gitlab,
+				Raw:          []byte(resMatch),
```
Comment (amanfcp) [inline pkg/detectors/gitlab/v1/gitlab.go:85]: In a single data string, if we have 2 set of credentials and only 2nd endpoint is correct, it would not be possible to identify why one result is verified and the other is not. 

```suggestion
				Raw:          []byte(resMatch),
				RawV2:      []byte(resMatch + endpoint),

```

Comment (kashifkhan0771) [reply pkg/detectors/gitlab/v1/gitlab.go:85]: I had considered this change but hesitated, concerned it might duplicate existing results in the Enterprise.
I think @rosecodym can comment better on this change.

Comment (shahzadhaider1) [reply pkg/detectors/gitlab/v1/gitlab.go:85]: Yup, you're right. Raw/RawV2 is like a primary key, and updating it even slightly can have impacts on the enterprise data, so let's not touch that. Instead, we can store the endpoint in the extra data.

Comment (amanfcp) [reply pkg/detectors/gitlab/v1/gitlab.go:85]: This could cause problems in diagnosing issues later on in enterprise too. This just might require migration. 
Also, I'm positive that "adding" a RawV2 won't require migration
@rosecodym awaiting your response.

Comment (dustin-decker) [reply pkg/detectors/gitlab/v1/gitlab.go:85]: Yes, adding a RawV2 that wasn't there before is fine and won't affect the deduplication fingerprinting.
Changing Raw or RawV2 will cause issues though.

Comment (kashifkhan0771) [reply pkg/detectors/gitlab/v1/gitlab.go:85]: Thanks @dustin-decker for the clarification - I updated the code.

**Review by amanfcp — APPROVED** [review]
LGTM! Thanks @kashifkhan0771
