### PR TITLE
Do not quit TUI, if 'q' is pressed on specific pages

### LINKED ISSUE #4352: Trufflehog analyze quits when pressing Q while a text input is selected
### TruffleHog Version
trufflehog 3.90.2

### Trace Output

```
trufflehog --log-level=5 analyze
2025-07-28T17:34:47+02:00	info-2	trufflehog	trufflehog 3.90.2
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2025-07-28T17:34:47+02:00	info-4	trufflehog	default engine options set
2025-07-28T17:34:47+02:00	info-4	trufflehog	engine initialized
2025-07-28T17:34:47+02:00	info-4	trufflehog	setting up aho-corasick core
2025-07-28T17:34:47+02:00	info-4	trufflehog	set up aho-corasick core
2025-07-28T17:34:47+02:00	info-2	trufflehog	starting scanner workers	{"count": 14}
2025-07-28T17:34:47+02:00	info-2	trufflehog	starting detector workers	{"count": 112}
2025-07-28T17:34:47+02:00	info-2	trufflehog	starting verificationOverlap workers	{"count": 14}
2025-07-28T17:34:47+02:00	info-2	trufflehog	starting notifier workers	{"count": 14}
2025-07-28T17:34:47+02:00	error	trufflehog	error running scan	{"error": "invalid command: analyze"}
```

### Expected Behavior

Any character should be allowed to be entered in a text field.

### Actual Behavior

Typing `q` as part of the text quits the analyzer.

### Steps to Reproduce

 1. Run `trufflehog analyze`
 2. Select any analyzer, e.g. Airbrake or GitHub
 3. Try to enter a secret or a log file name containing the letter `q`
 4. Analyzer exits

## Environment
 * OS: macOS
 * Version: 15.5

### References

* #0000

### PR DESCRIPTION
**Pull request by kashifkhan0771**
### Description:
Fixes #4352 

Screenshot from 2025-07-30 12-04-25

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/tui/tui.go [hunk 1]
```diff
@@ -143,6 +143,19 @@ func (ui *TUI) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 			switch {
 			case key.Matches(msg, ui.common.KeyMap.Help):
 			case key.Matches(msg, ui.common.KeyMap.CmdQuit) && ui.activePage() != sourceConfigurePage:
```
Comment (mcastorina) [inline pkg/tui/tui.go]: What about changing this to check `ui.activePage() == wizardIntroPage` so `q` only quits on the intro page?

Comment (kashifkhan0771) [reply pkg/tui/tui.go]: So we want 'q' to quit only on the `wizardIntroPage`?

Comment (kashifkhan0771) [reply pkg/tui/tui.go]: In my opinion, we should keep the quit behavior for `wizardIntroPage`, `analyzeKeysPage`, and `sourceSelectPage`, since we don’t manually enter any input on these pages.
