### PR TITLE
fix: fixed verification endpoint and verification logic for brand fetch

### LINKED ISSUE #3469: Issue with incorrect verification endpoint and verification logic for BrandFetch
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### Expected Behavior
The API endpoint should point to `v2` API with correct validation logic for token.

Reference : https://docs.brandfetch.com/reference/brand-api

#### Issue 1: Incorrect verification endpoint
Currently the API endpoint for verification points to `https://api.brandfetch.io/v1/color` which is nowhere to be found on the brandfetch.io documentation. They have upgraded to `v2` apis.

#### Issue 2: Incorrect validation logic
Currently the verification logic for the token is incorrect, which is according to the `v1` APIs which doesn't work anymore. 

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:
In this PR, we have added version 2 of the brandfetch detector. The following are the changes implemented:
1. Added a version 2 of the brandfetch detector that detects the latest brandfetch secret patterns
2. Added pattern and integration tests for v2
3. Updated the pattern and integration tests of v1 because they were failing
   - Fixed test patterns to use correct 44-character length secrets (43 base64 chars + 1 = padding)
   - Updated test cases to use realistic base64-like secret patterns
   - Added comprehensive test scenarios including assignment format, environment variables, and code contexts
   - Replaced invalid test patterns with properly malformed examples
   - Converted inline test secrets instead of using variables
4. Now both detector versions use the latest v2 version API of the brandfetch service

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

detector-brandfetch-tests

### CODE REVIEW

File: pkg/detectors/brandfetch/brandfetch.go [hunk 1]
```diff
@@ -47,15 +48,13 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
 		}
 
 		if verify {
-			payload := strings.NewReader(`{
-				"domain": "www.example.com"
-				}`)
-			req, err := http.NewRequestWithContext(ctx, "POST", "https://api.brandfetch.io/v1/color", payload)
+			// API upgraded to v2 from v1, new API doc:
```
Comment (kashifkhan0771) [inline pkg/detectors/brandfetch/brandfetch.go:51]: API documentation link is missing.

Comment (sahil9001) [reply pkg/detectors/brandfetch/brandfetch.go]: added, thanks @kashifkhan0771

File: pkg/detectors/brandfetch/brandfetch.go [hunk 2]
```diff
@@ -47,15 +48,13 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
 		}
 
 		if verify {
-			payload := strings.NewReader(`{
-				"domain": "www.example.com"
-				}`)
-			req, err := http.NewRequestWithContext(ctx, "POST", "https://api.brandfetch.io/v1/color", payload)
+			// API upgraded to v2 from v1, new API doc:  https://docs.brandfetch.com/reference/brand-api
+			req, err := http.NewRequestWithContext(ctx, "GET", "https://api.brandfetch.io/v2/brands/google.com", nil)
```
Comment (kashifkhan0771) [inline pkg/detectors/brandfetch/brandfetch.go:52]: The current `v1` APIs with the old tokens are still functioning properly. Therefore, rather than updating the existing version, I would recommend adding a new version of the detector.

File: pkg/detectors/brandfetch/brandfetch.go [hunk 3]
```diff
@@ -20,7 +21,7 @@ var (
 	client = common.SaneHttpClient()
 
 	// Make sure that your group is surrounded in boundary characters such as below to reduce false positives.
-	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"brandfetch"}) + `\b([0-9A-Za-z]{40})\b`)
+	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"brandfetch"}) + `\b([a-zA-Z0-9=]{44})`)
```
Comment (kashifkhan0771) [inline pkg/detectors/brandfetch/brandfetch.go:24]: The token I received included a `/` character as well. Its length was 44, which seems correct. I recommend generating multiple tokens to confirm the pattern.

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]

File: pkg/engine/defaults.go [hunk 4]
```diff
@@ -1642,6 +1642,8 @@ func DefaultDetectors() []detectors.Detector {
 		meraki.Scanner{},
 		saladcloudapikey.Scanner{},
 		boxoauth.Scanner{},
+		brandfetchV1.Scanner{},
```
Comment (kashifkhan0771) [inline pkg/engine/defaults.go:1645]: Missing Versioner interface implementation. For reference see any detector which has two versions(e.g Github, Gitlab etc)

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]

File: pkg/engine/defaults.go (hunk 4 above)
Comment (ahrav) [reply pkg/engine/defaults.go:1645]: I’ll create an issue to document this better since it can be confusing for most contributors. Even I find the interface smuggling confusing at times, so it’s likely unclear to others as well.

Comment (sahil9001) [reply pkg/engine/defaults.go:1645]: > Missing Versioner interface implementation


Can you give me an example of PR where this is implemented.

Comment (sahil9001) [reply pkg/engine/defaults.go:1644]: I have made the relevant changes.

File: pkg/detectors/brandfetch/v2/brandfetch_test.go [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+	"time"
+
+	"github.com/kylelemons/godebug/pretty"
+	"github.com/trufflesecurity/trufflehog/v3/pkg/detectors"
+
+	"github.com/trufflesecurity/trufflehog/v3/pkg/common"
+	"github.com/trufflesecurity/trufflehog/v3/pkg/pb/detectorspb"
+)
+
+func TestBrandfetch_FromChunk(t *testing.T) {
```
Comment (kashifkhan0771) [inline pkg/detectors/brandfetch/v2/brandfetch_test.go:19]: These test cases for v2 might fail as the regex is different and these v2 secrets does not exist in the vault.
I am not sure what to do here so tagging experts 👨🏻‍💻 @zricethezav @mcastorina @abmussani 

And please add the the pattern test cases for both versions separately.

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]

File: pkg/detectors/brandfetch/v2/brandfetch_test.go (hunk 5 above)
Comment (sahil9001) [reply pkg/detectors/brandfetch/v2/brandfetch_test.go:19]: Screenshot 2024-10-28 at 8 46 53 PM

Didn't get your point here, tests are passing, do you mean to add the tests which will fail in v2 but are of v1 pattern?

**Review by zricethezav — APPROVED** [review]

**Review by kashifkhan0771 — APPROVED** [review]

File: pkg/detectors/brandfetch/v2/brandfetch_test.go (hunk 5 above)
Comment (kashifkhan0771) [reply pkg/detectors/brandfetch/v2/brandfetch_test.go:19]: No worries! The pattern test cases will be covered as part of https://github.com/trufflesecurity/trufflehog/pull/3559

**Review by ahrav — APPROVED** [review]

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]
@sahil9001 can you resolve the conflicts. Changes are approved.

**Review by kashifkhan0771 — APPROVED** [review]

**Comment by sahil9001** [comment]
Hey @kashifkhan0771 sorry for the delay, can you check this again?

**Comment by kashifkhan0771** [comment]
> Hey @kashifkhan0771 sorry for the delay, can you check this again?

No worries @sahil9001 - The build is failing can you look into that?

File: pkg/detectors/brandfetch/v2/brandfetch.go [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+			}
+			req.Header.Add("Content-Type", "application/json")
+			req.Header.Add("Authorization", "Bearer "+resMatch)
+			res, err := client.Do(req)
+			if err == nil {
+				defer res.Body.Close()
+				if res.StatusCode >= 200 && res.StatusCode < 300 {
+					s1.Verified = true
+				}
+			}
```
Comment (nabeelalam) [inline pkg/detectors/brandfetch/v2/brandfetch.go]: @sahil9001, see my comment that I made on another pull request: https://github.com/trufflesecurity/trufflehog/pull/3414/files#r2163159831
I would suggest the same in this detector as well.

Comment (sahil9001) [reply pkg/detectors/brandfetch/v2/brandfetch.go]: done

**Comment by sahil9001** [comment]
@kashifkhan0771 @nabeelalam — Is this ready to merge? I see the tests working fine now.

**Comment by kashifkhan0771** [comment]
> @kashifkhan0771 @nabeelalam — Is this ready to merge? I see the tests working fine now.

The build is failing can you check

File: pkg/detectors/brandfetch/v2/brandfetch_test.go [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+	"testing"
+
+	"github.com/google/go-cmp/cmp"
+	"github.com/stretchr/testify/require"
+
+	"github.com/trufflesecurity/trufflehog/v3/pkg/detectors"
+	"github.com/trufflesecurity/trufflehog/v3/pkg/engine/ahocorasick"
+)
+
+func TestBrandFetch_Pattern(t *testing.T) {
```
Comment (kashifkhan0771) [inline pkg/detectors/brandfetch/v2/brandfetch_test.go:14]: Could you please align the pattern test cases with the updates I recently made for the A and B detectors?
Thanks in advance!

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]

File: pkg/detectors/brandfetch/v2/brandfetch_test.go (hunk 7 above)
Comment (shahzadhaider1) [reply pkg/detectors/brandfetch/v2/brandfetch_test.go:14]: done

**Review by kashifkhan0771 — APPROVED** [review]
Thanks @sahil9001 and @shahzadhaider1 ❤️
