### PR TITLE
fix(test/snowflake): Snowflake flaky pattern test

### LINKED ISSUE #3822: Flaky Snowflake unit tests
The Snowflake unit tests are flaky and periodically fail:
```
--- FAIL: TestSnowflake_Pattern (0.01s)
    --- FAIL: TestSnowflake_Pattern/Snowflake_Credentials (0.01s)
        snowflake_test.go:70: did not receive result
    --- FAIL: TestSnowflake_Pattern/Private_Snowflake_Credentials (0.00s)
        snowflake_test.go:70: did not receive result
    --- FAIL: TestSnowflake_Pattern/Snowflake_Credentials_-_Single_Character_account (0.00s)
        snowflake_test.go:70: did not receive result
FAIL
FAIL	github.com/trufflesecurity/trufflehog/v3/pkg/detectors/snowflake	0.618s
```

This is presumably due to the use of [brianvoe/gofakeit](https://github.com/brianvoe/gofakeit) to generate values.
https://github.com/trufflesecurity/trufflehog/blob/def734a783b2d4542f2b353d326130d618f3c421/pkg/detectors/snowflake/snowflake_test.go#L14-L16

----

I don't know if these are valid results being missed, or invalid generated values that ought to be skipped.

### PR DESCRIPTION
**Pull request by abmussani**
### Description:
Due to `gofakeit` library sometimes generated pattern for username and password were not detected by `snowflake` detector. This PR uses hardcoded define patterns instead of generating them at runtime. Also, includes one more test about invalid pattern.

Closes: #3822 

Test Output:
```
$ go test ./pkg/detectors/snowflake/
ok  	github.com/trufflesecurity/trufflehog/v3/pkg/detectors/snowflake	1.992s
```

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Review by kashifkhan0771 — APPROVED** [review]
Thanks @abmussani for fixing this ❤️

File: pkg/detectors/snowflake/snowflake_test.go [hunk 1]
```diff
@@ -5,15 +5,20 @@ import (
...
 
-	"github.com/brianvoe/gofakeit/v7"
 	"github.com/google/go-cmp/cmp"
 	"github.com/trufflesecurity/trufflehog/v3/pkg/detectors"
 	"github.com/trufflesecurity/trufflehog/v3/pkg/engine/ahocorasick"
 )
 
 func TestSnowflake_Pattern(t *testing.T) {
-	username := gofakeit.Username()
-	password := gofakeit.Password(true, true, true, false, false, 10)
```
Comment (rgmz) [inline pkg/detectors/snowflake/snowflake_test.go:16]: IMO, using a hard-coded value is a step backwards. The generated passwords failing likely indicate a pattern issue, or perhaps a test setup issue.

Comment (abmussani) [reply pkg/detectors/snowflake/snowflake_test.go:16]: Thanks for pointing this out. I was looking into the code of gofakeit module. The boolean as inputs control what characters are allowed in generated password but not guaranteed the inclusion. The snowflake password has a logic to ignore password which does not meet [the criteria](https://github.com/trufflesecurity/trufflehog/blob/b2ed7caeec8c1735fd5dd810095c531d877ac987/pkg/detectors/snowflake/snowflake.go#L88). When the generated password does not meet snowflake standard, the test gets break. 

For the same of simplicity, Like other pattern tests, I lean toward using hard-coded values. we could have write custom password generator to make sure it meets all the criteria. I avoided the complex path. 

Let me know what are your thoughts on this.

Comment (rgmz) [reply pkg/detectors/snowflake/snowflake_test.go:16]: Hard-coded values are a weakness that diminishes the value of tests. Have a large number of diverse cases can mitigate this, however, dynamically generating the values significantly increases the tests effectiveness. This is why things like fuzzing are so powerful.

You *can* use a single hard-coded value, but if the pattern is wrong and the test case is based on the pattern, it won't help catch real-world issues.

Comment (abmussani) [reply pkg/detectors/snowflake/snowflake_test.go:16]: I have written a function to generate a password with inclusion policy.

**Review by kashifkhan0771 — APPROVED** [review]

**Review by nabeelalam — APPROVED** [review]
LGTM; Thank you. The `generatePassword` function can be useful for other test cases as well.
