### PR TITLE
fix: fixed verification logic & endpoint for AyrShare

### LINKED ISSUE #3451: Issue with incorrect validation logic for AyrShare
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

[Version information to be added by user]

### Trace Output

[Trace output link to be added by user]

### Expected Behavior

The regex pattern `\b([A-Z]{7}-[A-Z0-9]{7}-[A-Z0-9]{7}-[A-Z0-9]{7})\b` should match the key `BBBB2222-BBBB2222-A2D2BE5D-7516B634`.

### Actual Behavior

The regex pattern does not match the provided key.

### Steps to Reproduce

1. Use the regex pattern `\b([A-Z]{7}-[A-Z0-9]{7}-[A-Z0-9]{7}-[A-Z0-9]{7})\b`
2. Attempt to match it against the key `BBBB2222-BBBB2222-A2D2BE5D-7516B634`
3. Observe that the regex fails to match the key

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

[To be filled by user]

## Additional Context

The issue is in the first group of the regex pattern. It expects 7 uppercase letters (`[A-Z]{7}`), but the key starts with `BBBB2222`, which includes numbers. Additionally, each group in the key contains 8 characters, not 7.

A corrected regex pattern would be:
`\b([A-Z0-9]{8}-[A-Z0-9]{8}-[A-Z0-9]{8}-[A-Z0-9]{8})\b`

This modified regex should correctly match the provided key.

### References

* [Any related issues or pull requests to be added by user]

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:
Fixes #3451 , tests screenshots:
Screenshot 2024-10-17 at 3 04 37 PM

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Comment by sahil9001** [comment]
@rgmz @zricethezav

**Comment by rgmz** [comment]
Please don't ping me for every change that you make.

**Comment by sahil9001** [comment]
> Please don't ping me for every change that you make.

Sure, sorry for that.

**Comment by sahil9001** [comment]
I thought you were an active contributor, so added you, else I don't know who is managing Hacktoberfest here.

File: pkg/detectors/ayrshare/ayrshare.go [hunk 1]
```diff
@@ -21,7 +22,7 @@ var (
 	client = common.SaneHttpClient()
 
 	// Make sure that your group is surrounded in boundary characters such as below to reduce false positives.
-	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"ayrshare"}) + `\b([A-Z]{7}-[A-Z0-9]{7}-[A-Z0-9]{7}-[A-Z0-9]{7})\b`)
+	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"ayrshare"}) + `\b([A-Z0-9]{8}-[A-Z0-9]{8}-[A-Z0-9]{8}-[A-Z0-9]{8})\b`)
```
Comment (kashifkhan0771) [inline pkg/detectors/ayrshare/ayrshare.go:25]: Has the Ayrshare secret pattern been updated? This is a critical change and should only be made once we are certain that the secret pattern has been updated correctly.

Comment (kashifkhan0771) [reply pkg/detectors/ayrshare/ayrshare.go:25]: I generated three API keys on [AyrShare](https://app.ayrshare.com/api), and it seems they've updated the pattern. The old regex is no longer detecting the keys.

Comment (sahil9001) [reply pkg/detectors/ayrshare/ayrshare.go:25]: Yes, I too tried with different keys, seems like they are using 8 characters now instead of 7,

File: pkg/detectors/ayrshare/ayrshare.go [hunk 2]
```diff
@@ -48,7 +49,7 @@ func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) (result
 		}
 
 		if verify {
-			req, err := http.NewRequestWithContext(ctx, "GET", "https://app.ayrshare.com/api/analytics/links", nil)
+			req, err := http.NewRequestWithContext(ctx, "GET", "https://app.ayrshare.com/api/user", nil)
```
Comment (kashifkhan0771) [inline pkg/detectors/ayrshare/ayrshare.go:52]: The `/user` API returns useful information, such as the user's email, which can be included in the extra data. 
I also recommend reviewing the [status code documentation](https://docs.ayrshare.com/rest-api/errors/http-status-codes) to handle responses appropriately.

**Review by kashifkhan0771 — CHANGES_REQUESTED** [review]

File: pkg/detectors/ayrshare/ayrshare.go (hunk 2 above)
Comment (sahil9001) [reply pkg/detectors/ayrshare/ayrshare.go:54]: done

**Review by kashifkhan0771 — APPROVED** [review]
Thank you @sahil9001 for fixing this detector regex. Changes LGTM!

**Comment by zricethezav** [comment]
First official hacktoberfest-2024 merged PR 🥂. Nice work.
