### PR TITLE
Fix GitHub source showing 0 members

### LINKED ISSUE #2198: GitHub `--include-members` always logs 0 members
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

3.63.2

### Expected Behavior

The log output specifies how many members an organization has.

```
2023-12-10T07:44:07-05:00       info-0  trufflehog      Adding repos    {"members": 18, "orgs": 1}
2023-12-10T07:44:07-05:00       info-0  trufflehog      Fetching repos from members     {"members": 18}
```

### Actual Behavior

The log output always says `"members": 0`

```
2023-12-10T07:44:07-05:00       info-0  trufflehog      Adding repos    {"members": 0, "orgs": 1}
2023-12-10T07:44:07-05:00       info-0  trufflehog      Fetching repos from members     {"members": 0}
```

This appears to be caused by the log using `len(s.members)` instead of `s.memberCache`. My guess is that the code was refactored at some point but not all instances of `s.members` were replaced with `s.memberCache`.
https://github.com/trufflesecurity/trufflehog/blob/331336dc0a6069f3cade033db914e79ee5dfda92/pkg/sources/github/github.go#L634-L635
https://github.com/trufflesecurity/trufflehog/blob/331336dc0a6069f3cade033db914e79ee5dfda92/pkg/sources/github/github.go#L1051

### Steps to Reproduce

Run TruffleHog against an org that has public members.

```sh
$ trufflehog github --org="git" --token=github_pat_rick --include-members --only-verified
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2023-12-10T07:44:07-05:00       info-0  trufflehog      Adding repos    {"members": 0, "orgs": 1}
2023-12-10T07:44:07-05:00       info-0  trufflehog      Fetching repos from members     {"members": 0}
...
```

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This fixes #2198.

```
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2023-12-11T09:43:05-05:00       info-0  trufflehog      Adding repos    {"members": 18, "orgs": 1}
2023-12-11T09:43:05-05:00       info-0  trufflehog      Fetching repos from members     {"members": 18}
```

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Review by ahrav — APPROVED** [review]
thank you!

File: pkg/sources/github/github.go [hunk 1]
```diff
@@ -702,8 +701,8 @@ func (s *Source) enumerateWithApp(ctx context.Context, apiEndpoint string, app *
 			if err != nil {
 				return nil, err
 			}
-			s.log.Info("Scanning repos", "org_members", len(s.members))
-			for _, member := range s.members {
+			s.log.Info("Scanning repos", "org_members", len(s.memberCache))
+			for member, _ := range s.memberCache {
```
Comment (ahrav) [inline pkg/sources/github/github.go:705]: nit: looks like an unnecessary assignment here since we just need the member key.

Comment (rgmz) [reply pkg/sources/github/github.go:705]: Good point. I'll remove that.
