### PR TITLE
fixed github issue 3821 for string shannon entropy test

### LINKED ISSUE #3821: Flaky `TestStringShannonEntropy` test
The [`TestStringShannonEntropy`](https://github.com/trufflesecurity/trufflehog/blob/def734a783b2d4542f2b353d326130d618f3c421/pkg/detectors/falsepositives_test.go#L153-L157) test fails periodically due to precision issues. 

This level of precision is unnecessary, and the tests should probably round to ~2 digits of precision.

```
 --- FAIL: TestStringShannonEntropy (0.00s)
    --- FAIL: TestStringShannonEntropy/entropy_2 (0.00s)
        falsepositives_test.go:177: StringShannonEntropy() = 0.22228483068568813, want 0.22228483068568816
    --- FAIL: TestStringShannonEntropy/entropy_3 (0.00s)
        falsepositives_test.go:177: StringShannonEntropy() = 0.22228483068568813, want 0.22228483068568816
FAIL
```

### PR DESCRIPTION
**Pull request by kashifkhan0771**
### Description:
This issue fixes the issue #3821 by rounding the output of shannon entropy output to two digits to avoid unnecessary precision.
 
Screenshot from 2024-12-30 15-35-43

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

File: pkg/detectors/falsepositives_test.go [hunk 1]
```diff
@@ -173,7 +174,8 @@ func TestStringShannonEntropy(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			if got := StringShannonEntropy(tt.args.input); got != tt.want {
+			got := roundToTwoDigits(StringShannonEntropy(tt.args.input))
```
Comment (ahrav) [inline pkg/detectors/falsepositives_test.go:177]: suggestion: I think we can rely on our testing package to handle most of the heavy lifting here

Ex:
```
got := StringShannonEntropy(tt.args.input)
if len(tt.args.input) > 0 && tt.want != 0 {
    assert.InEpsilon(t, tt.want, got, 0.1)
} else {
    assert.Equal(t, tt.want, got)
}
```

**Review by ahrav — APPROVED** [review]

File: pkg/detectors/falsepositives_test.go (hunk 1 above)
Comment (kashifkhan0771) [reply pkg/detectors/falsepositives_test.go]: That's cool! I didn't know about `InEpsilon`. Thanks for sharing. I updated the PR.

Comment (ahrav) [reply pkg/detectors/falsepositives_test.go]: I only just learned about it last week too. 😅
