### PR TITLE
[fix] - use typed const

### LINKED ISSUE #3791: Build fails on 32-bit systems: cannot use defaultMaxDiffSize (untyped int constant 2147483648) as int value in struct literal (overflows)
Build fails.

Errors:
```
pkg/gitparse/gitparse.go:213:18: cannot use defaultMaxDiffSize (untyped int constant 2147483648) as int value in struct literal (overflows)
pkg/gitparse/gitparse.go:214:18: cannot use defaultMaxCommitSize (untyped int constant 2147483648) as int value in struct literal (overflows)
```

[log](https://pkg-status.freebsd.org/beefy17/data/main-i386-default/p545eb5d3ac42_sda2c88dfcf4/logs/trufflehog-3.86.1.log)

Version: 3.86.1
go1.21

### PR DESCRIPTION
**Pull request by ahrav**
### Description:
This PR uses typed int64 constants to prevent overflow on 32-bit platforms for `defaultMaxSize` and `defaultCommitSize`. This can happen because integer constants in Go are initially untyped and can hold arbitrarily large values. The overflow issue arises when the compiler tries to assign that constant to a typed entity that cannot represent its value.
### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Review by abmussani — APPROVED** [review]
Nice ❤️

File: pkg/gitparse/gitparse.go [hunk 1]
```diff
@@ -210,8 +210,8 @@ type Option func(*Parser)
 func NewParser(options ...Option) *Parser {
 	parser := &Parser{
 		dateFormat:    defaultDateFormat,
-		maxDiffSize:   defaultMaxDiffSize,
-		maxCommitSize: defaultMaxCommitSize,
+		maxDiffSize:   int(defaultMaxDiffSize),
+		maxCommitSize: int(defaultMaxCommitSize),
```
Comment (abmussani) [inline pkg/gitparse/gitparse.go:214]: why narrow casting here ? Gopher won't throw error but might loss data silently.

Comment (ahrav) [reply pkg/gitparse/gitparse.go:214]: Ah, yep. Good call, this will actually break on 32-bit machines. I'll create a new PR to address this. Thanks for keeping me honest.

Comment (abmussani) [reply pkg/gitparse/gitparse.go:214]: I should have catch it before approving the PR. Sorry about that.

Comment (ahrav) [reply pkg/gitparse/gitparse.go:214]: My eyes just glossed over the fact that I was undoing the earlier type change 🤣 
follow-up [PR](https://github.com/trufflesecurity/trufflehog/pull/3793)
